# dockerエンジンの対象バージョンに合わせる
version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      TZ: Asia/Tokyo
    ports:
      - "15432:$MYSQL_PORT"
    # ローカル側が3306だとtableplus等のクライアントツールから接続が出来ないため
    # stopでコンテナを落とすならDBのデータは消えないそうなのであえて永続化しない

  backend:
    environment:
      FRONT_ORIGINS: "$FRONT_DOMAIN:$FRONT_PORT"
      ALLOW_HOST_PORT: "$ALLOW_HOST:$BACK_PORT"
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend-rails-api
    networks:
      - default
      - interconnect
    ports:
      - "$BACK_PORT:$BACK_PORT"
    working_dir: /backend
    # こいつのおかげでctr+cした際にrails serverを切ってからコンテナを終了してくれる
    # 137のエラーを解決してくれている
    # 初回起動時のみだった。
    stop_signal: SIGINT
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    # docker run -iを意味する
    stdin_open: true
    # -tを意味する
    tty: true
networks:
  interconnect:
    name: interconnect
    external: true