# dockerエンジンの対象バージョンに合わせる
version: '3'

services:
  frontend:
    environment:
      NEXT_PUBLIC_API_URL: "$BACK_URL:$BACK_PORT"
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontend-nextjs
    working_dir: /frontend
    stop_signal: SIGINT
    volumes:
      - ./frontend:/frontend
    ports:
      - "$FRONT_PORT:$FRONT_PORT"
    # docker run -iを意味する
    stdin_open: true
    # -tを意味する
    tty: true