# dockerエンジンの対象バージョンに合わせる
version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: neumann_development
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '15432:3306'
    # ローカル側が3306だとtableplus等のクライアントツールから接続が出来ないため
    # stopでコンテナを落とすならDBのデータは消えないそうなのであえて永続化しない

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend-rails-api
    ports:
      - '8080:8080'
    working_dir: /backend
    # こいつのおかげでctr+cした際にrails serverを切ってからコンテナを終了してくれる
    # 137のエラーを解決してくれている
    # 初回起動時のみだった。
    stop_signal: SIGINT
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    # docker run -iを意味する
    stdin_open: true
    # -tを意味する
    tty: true
