version: '3'

services:
  proxy:
    environment:
      PROXY_PORT: $PROXY_PORT
    build:
      context: ./proxy/
      dockerfile: Dockerfile
    container_name: proxy
    working_dir: /proxy
    stop_signal: SIGINT
    volumes:
      - ./proxy:/proxy
    networks:
      - interconnect
    ports:
      - "$PROXY_PORT:$PROXY_PORT"
    stdin_open: true
    # -tを意味する
    tty: true
networks:
  interconnect:
    name: interconnect
    external: true
