name: Run rspec, rubocop

on:
  pull_request:
  push:
    branches:
      - master

env:
  FRONT_ORIGINS: localhost:3000
  ALLOW_HOST_PORT: backend:8080
  NEUMANN_DATABASE_HOST: 127.0.0.1
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  rspec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    timeout-minutes: 10
    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: neumann_test
          MYSQL_ROOT_PASSWORD: password
          TZ: Asia/Tokyo
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Database create and migrate
        run: |
          bundle install
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run rspec
        run: bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Run rubocop
        run: |
          bundle install
          bundle exec rubocop